// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEjaWLILGnKYAbNCEdP3dkiYLGgnEEVPo',
    appId: '1:395589240644:web:db5c46bc10116a5e61b911',
    messagingSenderId: '395589240644',
    projectId: 'shop-blind-box',
    authDomain: 'shop-blind-box.firebaseapp.com',
    storageBucket: 'shop-blind-box.firebasestorage.app',
    measurementId: 'G-WLNWRZ45QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRDRzE4CQF9zuU1qUz2if1gSCle6DQaNA',
    appId: '1:395589240644:android:ba27ae98c3c97c6761b911',
    messagingSenderId: '395589240644',
    projectId: 'shop-blind-box',
    storageBucket: 'shop-blind-box.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAckWc1k9RHqv6jxzvQxGEhIi7k4sgUVkA',
    appId: '1:395589240644:ios:046edb8277e8aaf061b911',
    messagingSenderId: '395589240644',
    projectId: 'shop-blind-box',
    storageBucket: 'shop-blind-box.firebasestorage.app',
    iosBundleId: 'com.example.blindBoxShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAckWc1k9RHqv6jxzvQxGEhIi7k4sgUVkA',
    appId: '1:395589240644:ios:046edb8277e8aaf061b911',
    messagingSenderId: '395589240644',
    projectId: 'shop-blind-box',
    storageBucket: 'shop-blind-box.firebasestorage.app',
    iosBundleId: 'com.example.blindBoxShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEjaWLILGnKYAbNCEdP3dkiYLGgnEEVPo',
    appId: '1:395589240644:web:4dbcb2d77099103361b911',
    messagingSenderId: '395589240644',
    projectId: 'shop-blind-box',
    authDomain: 'shop-blind-box.firebaseapp.com',
    storageBucket: 'shop-blind-box.firebasestorage.app',
    measurementId: 'G-ETLBRHT2JH',
  );
}
